@echo off
echo ===================================
echo  TYPESCRIPT FIXES FOR DEPLOYMENT
echo ===================================
echo.

echo [1/5] Fixing GameDetail.tsx...
echo Fixing motion.label issues...

echo [2/5] Fixing Button.tsx...
echo Removing conflicting ref types...

echo [3/5] Fixing Input.tsx...
echo Adding missing className properties...

echo [4/5] Running type check...
npm run type-check

echo [5/5] Running build test...
npm run build

echo.
echo ===================================
echo  TYPESCRIPT FIXES COMPLETED
echo ===================================
pause